version: '3.8'

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile 
    image: huyvantrinh3008/ltu-backend:latest
    container_name: api
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app/backend
      - /app/backend/node_modules
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    image: huyvantrinh3008/ltu-frontend:latest
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - api
    networks:
      - app-network
    restart: unless-stopped
    stdin_open: true
    tty: true

networks:
  app-network:
    driver: bridge
