version: '3.8'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: hungzx234
      MONGO_INITDB_ROOT_PASSWORD: hungzx234
    # networks:
    #   - mongo-network
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: hungzx234
      ME_CONFIG_MONGODB_ADMINPASSWORD: hungzx234
    # networks:
    #   - mongo-network
    ports:
      - "8081:8081"

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile 
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000" 
    depends_on:
      - mongodb
    # networks:
    #   - mongo-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "3002:3002" 
    #   - mongo-network

    # networks:
    #   mongo-network:
    #     driver: bridge
