version: '3.8'

services:
  api:
    image: huyvantrinh3008/ltu-backend:latest
    container_name: backend
    env_file:
      - .env
    ports:
      - "5000:5000"
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    image: huyvantrinh3008/ltu-frontend:latest
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
